### ISSUE TITLE
Make error while building hpl: Undefined reference to symbol 'pthread_create@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by glowvey** [Jason23347/linpack-installer#1]
# The process of installing hpl-2.3
![2020-05-07 15-25-42 的屏幕截图](https://user-images.githubusercontent.com/51307440/81266656-b5926680-9077-11ea-9b48-f703702cee1d.png)

**Comment by Jason23347** [comment]
This bug was fixed in commit bb2b9d9.
